// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Container2;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Container3;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Container4;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Container5;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Container6;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Container7;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label7;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Container9;
void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Container10;
void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_TextArea1;
void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Label11;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Container11;
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Container12;
void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Container13;
void ui_event_Button14(lv_event_t * e);
extern lv_obj_t * ui_Button14;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_TextArea2;
void ui_event_Button15(lv_event_t * e);
extern lv_obj_t * ui_Button15;
extern lv_obj_t * ui_Label15;
// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Container14;
extern lv_obj_t * ui_Button16;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Container15;
void ui_event_Button17(lv_event_t * e);
extern lv_obj_t * ui_Button17;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Container16;
void ui_event_Button18(lv_event_t * e);
extern lv_obj_t * ui_Button18;
extern lv_obj_t * ui_Label18;
void ui_event_Button19(lv_event_t * e);
extern lv_obj_t * ui_Button19;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Roller1;
// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Container17;
extern lv_obj_t * ui_Button20;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Container18;
void ui_event_Button21(lv_event_t * e);
extern lv_obj_t * ui_Button21;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Container19;
void ui_event_Button22(lv_event_t * e);
extern lv_obj_t * ui_Button22;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_TextArea3;
void ui_event_Button23(lv_event_t * e);
extern lv_obj_t * ui_Button23;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Container29;
void ui_event_Button33(lv_event_t * e);
extern lv_obj_t * ui_Button33;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_Container30;
void ui_event_Button34(lv_event_t * e);
extern lv_obj_t * ui_Button34;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_TextArea9;
// SCREEN: ui_Screen6
void ui_Screen6_screen_init(void);
extern lv_obj_t * ui_Screen6;
extern lv_obj_t * ui_Container20;
extern lv_obj_t * ui_Button24;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Container21;
void ui_event_Button25(lv_event_t * e);
extern lv_obj_t * ui_Button25;
extern lv_obj_t * ui_Label25;
void ui_event_Button26(lv_event_t * e);
extern lv_obj_t * ui_Button26;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_TextArea4;
void ui_event_Button27(lv_event_t * e);
extern lv_obj_t * ui_Button27;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Container27;
void ui_event_Button30(lv_event_t * e);
extern lv_obj_t * ui_Button30;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_Container28;
void ui_event_Button32(lv_event_t * e);
extern lv_obj_t * ui_Button32;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_TextArea8;
// SCREEN: ui_Screen7
void ui_Screen7_screen_init(void);
extern lv_obj_t * ui_Screen7;
extern lv_obj_t * ui_Container23;
extern lv_obj_t * ui_Button28;
extern lv_obj_t * ui_Label28;
void ui_event_Button31(lv_event_t * e);
extern lv_obj_t * ui_Button31;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_Container24;
extern lv_obj_t * ui_Label29;
void ui_event_TextArea5(lv_event_t * e);
extern lv_obj_t * ui_TextArea5;
extern lv_obj_t * ui_Container26;
extern lv_obj_t * ui_Label32;
void ui_event_TextArea7(lv_event_t * e);
extern lv_obj_t * ui_TextArea7;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_bankground_png);    // assets/bankground.png
LV_IMG_DECLARE(ui_img_qwq_png);    // assets/qwq.png
LV_IMG_DECLARE(ui_img_fanyhi_png);    // assets/fanyhi.png



LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_Font2);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
