// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void MicroPhone_Reconfig(lv_event_t * e);
void MicroPhone_Reconfig_End(lv_event_t * e);
void Press_Electric(lv_event_t * e);
void Press_Electric_End(lv_event_t * e);
void MicroPhone_Contant(lv_event_t * e);
void MicroPhone_Contant_End(lv_event_t * e);
void Tcp_AI_Q_A_Begin(lv_event_t * e);
void Tcp_AI_Q_A_End(lv_event_t * e);
void Tcp_AI_Q_A_Clear(lv_event_t * e);
void Tcp_AI_Q_A_Deter(lv_event_t * e);
void Tcp_Machine_Begin(lv_event_t * e);
void Tcp_Machine_End(lv_event_t * e);
void Tcp_Machine_Clear(lv_event_t * e);
void Tcp_Machine_Deter(lv_event_t * e);
void Wifi_Connect(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
