// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen7_screen_init(void)
{
    ui_Screen7 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Screen7, &ui_img_bankground_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container23 = lv_obj_create(ui_Screen7);
    lv_obj_remove_style_all(ui_Container23);
    lv_obj_set_width(ui_Container23, 260);
    lv_obj_set_height(ui_Container23, 60);
    lv_obj_set_x(ui_Container23, 0);
    lv_obj_set_y(ui_Container23, -210);
    lv_obj_set_align(ui_Container23, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container23, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button28 = lv_btn_create(ui_Container23);
    lv_obj_set_width(ui_Button28, 260);
    lv_obj_set_height(ui_Button28, 60);
    lv_obj_set_align(ui_Button28, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button28, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button28, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label28 = lv_label_create(ui_Button28);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "网络连接");
    lv_obj_set_style_text_font(ui_Label28, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button31 = lv_btn_create(ui_Screen7);
    lv_obj_set_width(ui_Button31, 100);
    lv_obj_set_height(ui_Button31, 50);
    lv_obj_set_x(ui_Button31, 343);
    lv_obj_set_y(ui_Button31, -210);
    lv_obj_set_align(ui_Button31, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button31, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button31, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label31 = lv_label_create(ui_Button31);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "返回");
    lv_obj_set_style_text_font(ui_Label31, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_Screen7);
    lv_obj_set_width(ui_Keyboard1, 800);
    lv_obj_set_height(ui_Keyboard1, 240);
    lv_obj_set_x(ui_Keyboard1, 0);
    lv_obj_set_y(ui_Keyboard1, 120);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);

    ui_Container24 = lv_obj_create(ui_Screen7);
    lv_obj_remove_style_all(ui_Container24);
    lv_obj_set_width(ui_Container24, 250);
    lv_obj_set_height(ui_Container24, 50);
    lv_obj_set_x(ui_Container24, -180);
    lv_obj_set_y(ui_Container24, -65);
    lv_obj_set_align(ui_Container24, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container24, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container24, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_Container24);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, -92);
    lv_obj_set_y(ui_Label29, 0);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "WIFI");

    ui_TextArea5 = lv_textarea_create(ui_Container24);
    lv_obj_set_width(ui_TextArea5, 165);
    lv_obj_set_height(ui_TextArea5, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_TextArea5, 37);
    lv_obj_set_y(ui_TextArea5, -1);
    lv_obj_set_align(ui_TextArea5, LV_ALIGN_CENTER);



    ui_Container26 = lv_obj_create(ui_Screen7);
    lv_obj_remove_style_all(ui_Container26);
    lv_obj_set_width(ui_Container26, 250);
    lv_obj_set_height(ui_Container26, 50);
    lv_obj_set_x(ui_Container26, 143);
    lv_obj_set_y(ui_Container26, -65);
    lv_obj_set_align(ui_Container26, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container26, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container26, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label32 = lv_label_create(ui_Container26);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label32, -88);
    lv_obj_set_y(ui_Label32, 0);
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "password");

    ui_TextArea7 = lv_textarea_create(ui_Container26);
    lv_obj_set_width(ui_TextArea7, 165);
    lv_obj_set_height(ui_TextArea7, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_TextArea7, 37);
    lv_obj_set_y(ui_TextArea7, -1);
    lv_obj_set_align(ui_TextArea7, LV_ALIGN_CENTER);



    lv_obj_add_event_cb(ui_Button31, ui_event_Button31, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea5, ui_event_TextArea5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea7, ui_event_TextArea7, LV_EVENT_ALL, NULL);

}
