// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Screen4, &ui_img_bankground_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container14 = lv_obj_create(ui_Screen4);
    lv_obj_remove_style_all(ui_Container14);
    lv_obj_set_width(ui_Container14, 260);
    lv_obj_set_height(ui_Container14, 60);
    lv_obj_set_x(ui_Container14, 0);
    lv_obj_set_y(ui_Container14, -210);
    lv_obj_set_align(ui_Container14, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button16 = lv_btn_create(ui_Container14);
    lv_obj_set_width(ui_Button16, 260);
    lv_obj_set_height(ui_Button16, 60);
    lv_obj_set_align(ui_Button16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button16, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button16, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label16 = lv_label_create(ui_Button16);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "双向通话");
    lv_obj_set_style_text_font(ui_Label16, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container15 = lv_obj_create(ui_Screen4);
    lv_obj_remove_style_all(ui_Container15);
    lv_obj_set_width(ui_Container15, 220);
    lv_obj_set_height(ui_Container15, 50);
    lv_obj_set_x(ui_Container15, -200);
    lv_obj_set_y(ui_Container15, -80);
    lv_obj_set_align(ui_Container15, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button17 = lv_btn_create(ui_Container15);
    lv_obj_set_width(ui_Button17, 220);
    lv_obj_set_height(ui_Button17, 50);
    lv_obj_set_align(ui_Button17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button17, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label17 = lv_label_create(ui_Button17);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "开始通话");
    lv_obj_set_style_text_font(ui_Label17, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container16 = lv_obj_create(ui_Screen4);
    lv_obj_remove_style_all(ui_Container16);
    lv_obj_set_width(ui_Container16, 220);
    lv_obj_set_height(ui_Container16, 50);
    lv_obj_set_x(ui_Container16, 200);
    lv_obj_set_y(ui_Container16, -80);
    lv_obj_set_align(ui_Container16, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container16, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button18 = lv_btn_create(ui_Container16);
    lv_obj_set_width(ui_Button18, 220);
    lv_obj_set_height(ui_Button18, 50);
    lv_obj_set_align(ui_Button18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button18, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label18 = lv_label_create(ui_Button18);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "通话结束");
    lv_obj_set_style_text_font(ui_Label18, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button19 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button19, 100);
    lv_obj_set_height(ui_Button19, 50);
    lv_obj_set_x(ui_Button19, 343);
    lv_obj_set_y(ui_Button19, -210);
    lv_obj_set_align(ui_Button19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button19, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label19 = lv_label_create(ui_Button19);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "返回");
    lv_obj_set_style_text_font(ui_Label19, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roller1 = lv_roller_create(ui_Screen4);
    lv_roller_set_options(ui_Roller1, "麦克风信号\n压电信号", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_Roller1, 200);
    lv_obj_set_height(ui_Roller1, 143);
    lv_obj_set_x(ui_Roller1, 4);
    lv_obj_set_y(ui_Roller1, 94);
    lv_obj_set_align(ui_Roller1, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_Roller1, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller1, lv_color_hex(0x51C1DD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Roller1, lv_color_hex(0x227685), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller1, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button17, ui_event_Button17, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button18, ui_event_Button18, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button19, ui_event_Button19, LV_EVENT_ALL, NULL);

}
