// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Screen5, &ui_img_bankground_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container17 = lv_obj_create(ui_Screen5);
    lv_obj_remove_style_all(ui_Container17);
    lv_obj_set_width(ui_Container17, 260);
    lv_obj_set_height(ui_Container17, 60);
    lv_obj_set_x(ui_Container17, 0);
    lv_obj_set_y(ui_Container17, -210);
    lv_obj_set_align(ui_Container17, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container17, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button20 = lv_btn_create(ui_Container17);
    lv_obj_set_width(ui_Button20, 260);
    lv_obj_set_height(ui_Button20, 60);
    lv_obj_set_align(ui_Button20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button20, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button20, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label20 = lv_label_create(ui_Button20);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "AI问答");
    lv_obj_set_style_text_font(ui_Label20, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container18 = lv_obj_create(ui_Screen5);
    lv_obj_remove_style_all(ui_Container18);
    lv_obj_set_width(ui_Container18, 100);
    lv_obj_set_height(ui_Container18, 50);
    lv_obj_set_x(ui_Container18, -280);
    lv_obj_set_y(ui_Container18, -80);
    lv_obj_set_align(ui_Container18, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container18, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button21 = lv_btn_create(ui_Container18);
    lv_obj_set_width(ui_Button21, 100);
    lv_obj_set_height(ui_Button21, 50);
    lv_obj_set_align(ui_Button21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button21, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label21 = lv_label_create(ui_Button21);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "开始");
    lv_obj_set_style_text_font(ui_Label21, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container19 = lv_obj_create(ui_Screen5);
    lv_obj_remove_style_all(ui_Container19);
    lv_obj_set_width(ui_Container19, 100);
    lv_obj_set_height(ui_Container19, 50);
    lv_obj_set_x(ui_Container19, -100);
    lv_obj_set_y(ui_Container19, -80);
    lv_obj_set_align(ui_Container19, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container19, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button22 = lv_btn_create(ui_Container19);
    lv_obj_set_width(ui_Button22, 100);
    lv_obj_set_height(ui_Button22, 50);
    lv_obj_set_align(ui_Button22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button22, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label22 = lv_label_create(ui_Button22);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "结束");
    lv_obj_set_style_text_font(ui_Label22, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea3 = lv_textarea_create(ui_Screen5);
    lv_obj_set_width(ui_TextArea3, 640);
    lv_obj_set_height(ui_TextArea3, 150);
    lv_obj_set_x(ui_TextArea3, 52);
    lv_obj_set_y(ui_TextArea3, 164);
    lv_obj_set_align(ui_TextArea3, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea3, "结果:");
    lv_obj_set_style_text_font(ui_TextArea3, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Button23 = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_Button23, 100);
    lv_obj_set_height(ui_Button23, 50);
    lv_obj_set_x(ui_Button23, 343);
    lv_obj_set_y(ui_Button23, -210);
    lv_obj_set_align(ui_Button23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button23, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label23 = lv_label_create(ui_Button23);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "返回");
    lv_obj_set_style_text_font(ui_Label23, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Screen5);
    lv_img_set_src(ui_Image1, &ui_img_qwq_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, -288);
    lv_obj_set_y(ui_Image1, 173);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_Image1, 1, 1);
    lv_img_set_zoom(ui_Image1, 128);

    ui_Container29 = lv_obj_create(ui_Screen5);
    lv_obj_remove_style_all(ui_Container29);
    lv_obj_set_width(ui_Container29, 100);
    lv_obj_set_height(ui_Container29, 50);
    lv_obj_set_x(ui_Container29, 80);
    lv_obj_set_y(ui_Container29, -80);
    lv_obj_set_align(ui_Container29, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container29, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button33 = lv_btn_create(ui_Container29);
    lv_obj_set_width(ui_Button33, 100);
    lv_obj_set_height(ui_Button33, 50);
    lv_obj_set_align(ui_Button33, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button33, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button33, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label35 = lv_label_create(ui_Button33);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, "清空");
    lv_obj_set_style_text_font(ui_Label35, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container30 = lv_obj_create(ui_Screen5);
    lv_obj_remove_style_all(ui_Container30);
    lv_obj_set_width(ui_Container30, 100);
    lv_obj_set_height(ui_Container30, 50);
    lv_obj_set_x(ui_Container30, 260);
    lv_obj_set_y(ui_Container30, -80);
    lv_obj_set_align(ui_Container30, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container30, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button34 = lv_btn_create(ui_Container30);
    lv_obj_set_width(ui_Button34, 100);
    lv_obj_set_height(ui_Button34, 50);
    lv_obj_set_align(ui_Button34, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button34, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button34, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label36 = lv_label_create(ui_Button34);
    lv_obj_set_width(ui_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label36, "确认");
    lv_obj_set_style_text_font(ui_Label36, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea9 = lv_textarea_create(ui_Screen5);
    lv_obj_set_width(ui_TextArea9, 640);
    lv_obj_set_height(ui_TextArea9, 70);
    lv_obj_set_x(ui_TextArea9, 54);
    lv_obj_set_y(ui_TextArea9, 50);
    lv_obj_set_align(ui_TextArea9, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea9, "问题:");
    lv_obj_set_style_text_font(ui_TextArea9, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);



    lv_obj_add_event_cb(ui_Button21, ui_event_Button21, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button22, ui_event_Button22, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button23, ui_event_Button23, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button33, ui_event_Button33, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button34, ui_event_Button34, LV_EVENT_ALL, NULL);

}
