// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Screen6, &ui_img_bankground_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container20 = lv_obj_create(ui_Screen6);
    lv_obj_remove_style_all(ui_Container20);
    lv_obj_set_width(ui_Container20, 260);
    lv_obj_set_height(ui_Container20, 60);
    lv_obj_set_x(ui_Container20, 0);
    lv_obj_set_y(ui_Container20, -210);
    lv_obj_set_align(ui_Container20, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container20, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button24 = lv_btn_create(ui_Container20);
    lv_obj_set_width(ui_Button24, 260);
    lv_obj_set_height(ui_Button24, 60);
    lv_obj_set_align(ui_Button24, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button24, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button24, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label24 = lv_label_create(ui_Button24);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "机器翻译");
    lv_obj_set_style_text_font(ui_Label24, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container21 = lv_obj_create(ui_Screen6);
    lv_obj_remove_style_all(ui_Container21);
    lv_obj_set_width(ui_Container21, 100);
    lv_obj_set_height(ui_Container21, 50);
    lv_obj_set_x(ui_Container21, -280);
    lv_obj_set_y(ui_Container21, -80);
    lv_obj_set_align(ui_Container21, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container21, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button25 = lv_btn_create(ui_Container21);
    lv_obj_set_width(ui_Button25, 100);
    lv_obj_set_height(ui_Button25, 50);
    lv_obj_set_align(ui_Button25, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button25, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label25 = lv_label_create(ui_Button25);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "开始");
    lv_obj_set_style_text_font(ui_Label25, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button26 = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_Button26, 100);
    lv_obj_set_height(ui_Button26, 50);
    lv_obj_set_x(ui_Button26, -107);
    lv_obj_set_y(ui_Button26, -79);
    lv_obj_set_align(ui_Button26, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button26, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label26 = lv_label_create(ui_Button26);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "结束");
    lv_obj_set_style_text_font(ui_Label26, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea4 = lv_textarea_create(ui_Screen6);
    lv_obj_set_width(ui_TextArea4, 640);
    lv_obj_set_height(ui_TextArea4, 150);
    lv_obj_set_x(ui_TextArea4, 54);
    lv_obj_set_y(ui_TextArea4, 164);
    lv_obj_set_align(ui_TextArea4, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea4, "结果:");
    lv_obj_set_style_text_font(ui_TextArea4, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Button27 = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_Button27, 100);
    lv_obj_set_height(ui_Button27, 50);
    lv_obj_set_x(ui_Button27, 343);
    lv_obj_set_y(ui_Button27, -210);
    lv_obj_set_align(ui_Button27, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button27, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button27, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label27 = lv_label_create(ui_Button27);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "返回");
    lv_obj_set_style_text_font(ui_Label27, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_Image2, &ui_img_fanyhi_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, -333);
    lv_obj_set_y(ui_Image2, 163);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image2, 190);

    ui_Container27 = lv_obj_create(ui_Screen6);
    lv_obj_remove_style_all(ui_Container27);
    lv_obj_set_width(ui_Container27, 100);
    lv_obj_set_height(ui_Container27, 50);
    lv_obj_set_x(ui_Container27, 80);
    lv_obj_set_y(ui_Container27, -80);
    lv_obj_set_align(ui_Container27, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container27, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button30 = lv_btn_create(ui_Container27);
    lv_obj_set_width(ui_Button30, 100);
    lv_obj_set_height(ui_Button30, 50);
    lv_obj_set_align(ui_Button30, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button30, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button30, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label33 = lv_label_create(ui_Button30);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "清空");
    lv_obj_set_style_text_font(ui_Label33, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container28 = lv_obj_create(ui_Screen6);
    lv_obj_remove_style_all(ui_Container28);
    lv_obj_set_width(ui_Container28, 100);
    lv_obj_set_height(ui_Container28, 50);
    lv_obj_set_x(ui_Container28, 260);
    lv_obj_set_y(ui_Container28, -80);
    lv_obj_set_align(ui_Container28, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container28, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button32 = lv_btn_create(ui_Container28);
    lv_obj_set_width(ui_Button32, 100);
    lv_obj_set_height(ui_Button32, 50);
    lv_obj_set_align(ui_Button32, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button32, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button32, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label34 = lv_label_create(ui_Button32);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label34, "确定");
    lv_obj_set_style_text_font(ui_Label34, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea8 = lv_textarea_create(ui_Screen6);
    lv_obj_set_width(ui_TextArea8, 640);
    lv_obj_set_height(ui_TextArea8, 70);
    lv_obj_set_x(ui_TextArea8, 54);
    lv_obj_set_y(ui_TextArea8, 50);
    lv_obj_set_align(ui_TextArea8, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea8, "翻译:");
    lv_obj_set_style_text_font(ui_TextArea8, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);



    lv_obj_add_event_cb(ui_Button25, ui_event_Button25, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button26, ui_event_Button26, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button27, ui_event_Button27, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button30, ui_event_Button30, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button32, ui_event_Button32, LV_EVENT_ALL, NULL);

}
